{% set name = "sertit" %}
{% set version = "1.46.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sertit-{{ version }}.tar.gz
  sha256: 5e0d1244d81e416d85d67a4159c25487e38c36a3fb9d3504054671794b44e518

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - cloudpathlib >=0.12.1
    - dill
    - lxml
    - psutil
    - tqdm
    - cloudpathlib-s3 >=0.12.1
    - rasterio >=1.3.10
    - xarray >=2024.06.0
    - rioxarray >=0.10.0
    - geopandas >=0.14.4
    - dask >=2024.5.1
    - shapely >=2.0.0
    - odc-geo >=0.4.6
    - xarray-spatial >=0.3.6
    # https://github.com/coiled/benchmarks/issues/1616
    - cryptography >=43.0.3
    - pyopenssl >=24.2.1

test:
  imports:
    - sertit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/sertit/sertit-utils
  summary: SERTIT python library for generic tools.
  license: Apache-2.0
  license_file: LICENSE
  description: SERTIT python library for generic tools.
  doc_url: https://sertit-utils.readthedocs.io/en/latest
  dev_url: http://github.com/sertit/sertit-utils

extra:
  recipe-maintainers:
    - bastiencyr
    - qpoterek
    - remi-braun
