{% set name = "sertit" %}
{% set version = "1.41.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sertit-{{ version }}.tar.gz
  sha256: a165107e6e4b052bc7e9273a98225a41382479d496c7aaf6742eafe800f272ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - cloudpathlib >=0.10.0
    - dill
    - lxml
    - psutil
    - python >=3.9
    - tqdm
    - cloudpathlib-all >=0.10.0
    - rasterio >=1.3.0
    - xarray >=0.18.0
    - rioxarray >=0.4.0
    - geopandas >=0.11.0
    - dask >=2021.10.0
    - shapely >=2.0.0

test:
  imports:
    - sertit
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/sertit-utils
  summary: SERTIT python library for generic tools.
  license: Apache-2.0
  license_file: LICENSE
  description: SERTIT python library for generic tools.
  doc_url: https://sertit-utils.readthedocs.io/en/latest
  dev_url: http://github.com/sertit/sertit-utils

extra:
  recipe-maintainers:
    - remi-braun
