{% set name = "sertit" %}
{% set version = "1.42.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sertit-{{ version }}.tar.gz
  sha256: a832d7e177622a156f40bb0c72b5f3e8d45e58f2799de6a734cd2d48f30a09a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - dill
    - lxml
    - psutil
    - python >=3.9
    - tqdm
    - cloudpathlib-all >=0.12.1
    - rasterio >=1.3.10
    - xarray >=2024.06.0
    - rioxarray >=0.10.0
    - geopandas >=1.0.0
    - dask >=2024.5.1
    - shapely >=2.0.0

test:
  imports:
    - sertit
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/sertit-utils
  summary: SERTIT python library for generic tools.
  license: Apache-2.0
  license_file: LICENSE
  description: SERTIT python library for generic tools.
  doc_url: https://sertit-utils.readthedocs.io/en/latest
  dev_url: http://github.com/sertit/sertit-utils

extra:
  recipe-maintainers:
    - remi-braun
