{% set name = "sertit" %}
{% set version = "1.44.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sertit-{{ version }}.tar.gz
  sha256: 0e49f12643aee5467bf1e92d3d1e144ca783cb75be4021716eaeac683da67d09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 3.9
    - setuptools
  run:
    - python >=3.9
    - cloudpathlib >=0.12.1
    - dill
    - lxml
    - psutil
    - tqdm
    - cloudpathlib-all >=0.12.1
    - rasterio >=1.3.10
    - xarray >=2024.06.0
    - rioxarray >=0.10.0
    - geopandas >=0.14.4
    - dask >=2024.5.1
    - shapely >=2.0.0
    # https://github.com/coiled/benchmarks/issues/1616
    - cryptography >=43.0.3
    - pyopenssl >=24.2.1

test:
  imports:
    - sertit
  commands:
    - pip check
  requires:
    - pip
    - python 3.9

about:
  home: http://github.com/sertit/sertit-utils
  summary: SERTIT python library for generic tools.
  license: Apache-2.0
  license_file: LICENSE
  description: SERTIT python library for generic tools.
  doc_url: https://sertit-utils.readthedocs.io/en/latest
  dev_url: http://github.com/sertit/sertit-utils

extra:
  recipe-maintainers:
    - remi-braun
